<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

use Acquia\Blt\Robo\Common\EnvironmentDetector;
use Drupal\Core\Installer\InstallerKernel;
use Drupal\Core\Serialization\Yaml;

$settings['config_sync_directory'] = EnvironmentDetector::getRepoRoot() . '/config/default';

/**
 * Include settings files in docroot/sites/settings.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
$additionalSettingsFiles = [
  __DIR__ . '/simplesaml.php',
  __DIR__ . '/environment_indicator.php',
  __DIR__ . '/local.settings.php',
  __DIR__ . '/fast404.settings.php',
];

foreach ($additionalSettingsFiles as $settingsFile) {
  if (file_exists($settingsFile)) {
    // phpcs:ignore
    require $settingsFile;
  }
}

// When the encryption environment variable is not provided (local/ci/etc),
// fake the encryption string so that the site doesn't break.
if (!getenv('REAL_AES_ENCRYPTION')) {
  $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  $randomString = '';
  for ($i = 0; $i < 256 / 8; $i++) {
    $randomString .= $characters[rand(0, strlen($characters) - 1)];
  }
  putenv("REAL_AES_ENCRYPTION=$randomString");
}

// Lets whitelist everything because in our event subscriber we have the
// ability to decide which forms are locked.
// @see \Drupal\hs_config_readonly\EventSubscriber\ConfigReadOnlyEventSubscriber
$settings['config_readonly_whitelist_patterns'] = ['*'];

// Set the config_ignore settings so that config imports will function on local.
if (EnvironmentDetector::isLocalEnv() && !InstallerKernel::installationAttempted()) {
  $config_ignore = Yaml::decode(file_get_contents(DRUPAL_ROOT . '/../config/envs/local/config_ignore.settings.yml'));
  $config['config_ignore.settings']['ignored_config_entities'] = $config_ignore['ignored_config_entities'] + array_fill(0, 50, 'foo.bar.baz');
}

// Don't lock config when using drush.
if (PHP_SAPI !== 'cli') {
  $settings['config_readonly'] = TRUE;
}

if (EnvironmentDetector::isAhEnv()) {
  require 'acquia.settings.php';
}
else {
  $config['domain_301_redirect.settings']['enabled'] = FALSE;
  $config['mail_safety.settings']['enabled'] = TRUE;
  $config['mail_safety.settings']['send_mail_to_dashboard'] = TRUE;
}
