<?php

/**
 * @file
 * hs_events.mdoule
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeForm;

/**
 * Implements hook_entity_delete().
 */
function hs_events_entity_delete(EntityInterface $entity) {
  if ($entity instanceof Node && $entity->bundle() == 'hs_event') {
    $speakers = $entity->get('field_hs_event_speaker')->getValue();

    // When running a migration rollback the referenced entities are not deleted
    // so we have to delete them manually. Deleting via the UI does not have
    // the same issue.
    foreach ($speakers as $speaker_value) {
      $speaker = \Drupal::entityTypeManager()
        ->getStorage('event_collections')
        ->load($speaker_value['target_id']);
      if ($speaker) {
        $speaker->delete();
      }
    }
  }
}
