<?php

/**
 * @file
 * Contains hs_megamenu.module.
 */

/**
 * Implements hook_preprocess_menu().
 *
 * Target main menu and add a twig variable to show/hide the new mega menu.
 */
function hs_megamenu_preprocess_menu(&$variables) {

  if ($variables['menu_name'] == 'main') {
    $config_pages = \Drupal::service('config_pages.loader');
    $useMegaMenu = $config_pages->getValue('hs_site_options', 'field_en_mega_menu');
    $variables['use_hs_megamenu'] = $useMegaMenu[0]['value'];
  }
}
