<?php

/**
 * @file
 * mrc_events.mdoule
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_entity_delete().
 */
function mrc_events_entity_delete(EntityInterface $entity) {
  if ($entity instanceof Node && $entity->bundle() == 'stanford_event') {
    $speakers = $entity->get('field_s_event_speaker')->getValue();
    foreach ($speakers as $speaker_value) {
      $speaker = \Drupal::entityTypeManager()
        ->getStorage('event_collections')
        ->load($speaker_value['target_id']);
      if ($speaker) {
        $speaker->delete();
      }
    }
  }
}

/**
 * Implements hook_preprocess().
 */
function mrc_events_preprocess(&$variables, $hook) {
  // Limit the number of years in the date field.
  if ($hook == 'select' && strpos($variables['element']['#name'], 'field_s_event_date') !== FALSE) {
    if (strpos($variables['element']['#name'], '[year]') !== FALSE) {
      $this_year = (int) date('Y');
      foreach ($variables['options'] as $key => $option) {
        if (!(int) $option['value']) {
          continue;
        }

        $diff = abs($this_year - $option['value']);
        if ($diff > 31) {
          unset($variables['options'][$key]);
        }
      }
    }

  }
}
