su_humsci_admin.settings:
  type: theme_settings
  label: 'Material Admin settings'
  mapping:
    su_humsci_admin_node_actions:
      type: boolean
    su_humsci_admin_portal_login:
      type: boolean
    su_humsci_admin_jqueryui_dialog_background:
      type: boolean
    su_humsci_admin_jqueryui_dialog_close:
      type: boolean
    su_humsci_admin_collapse_module_list:
      type: boolean
    su_humsci_admin_message_length:
      type: integer
    su_humsci_admin_message_prompt:
      type: boolean
    su_humsci_admin_datepicker_select_years:
      type: integer
    su_humsci_admin_select_default:
      type: boolean
