<?php

/**
 * @file
 * su_humsci_admin.theme
 */

/**
 * Implements hook_preprocess_page().
 */
function su_humsci_admin_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'entity.node.edit_form') {
    // We add the library here because a hook_form_alter doesn't work.
    $variables['#attached']['library'][] = 'su_humsci_admin/node_protection';
  }
}
