hs_revision_cleanup.settings:
  type: mapping
  mapping:
    langcode:
      type: string
      label: 'Language code'
    _core:
      type: _core_config_info
    cleanup:
      type: sequence
      label: "Cleanup Entities"
      sequence:
        type: mapping
        mapping:
          entity_type:
            type: string
            label: "Entity Type ID"
          keep:
            type: integer
            label: "Revisions to keep"