# see https://github.com/marketplace/actions/labeler
# Tag the PR as a patch release if the profile version has changed.
patch:
  - 'docroot/**/*profile.info.yml'

js:
  - docroot/**/*.js

css:
  - docroot/**/*.scss
  - docroot/**/*.css

php:
  - docroot/**/*.php
  - docroot/**/*.module
  - docroot/**/*.theme

ci:
  - blt/*
  - blt/**/*
  - .circleci/*
  - .circleci/**/*
  - .github/*
  - .github/**/*
