ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001-8999
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - name: SSH Keys
    before: |
      mkdir -p ~/.ssh
      if [[ ! -z $SSH_PRIVATE_KEY ]]; then
          echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa &&
          git remote set-url origin git@github.com:SU-HSDO/suhumsci.git
      fi
      if [[ ! -z $GITCONFIG ]]; then
          echo $GITCONFIG | base64 -d > ~/.gitconfig && chmod 644 ~/.gitconfig
      fi
    init: >
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      cp .gitpod/blt.yml blt/local.blt.yml &&
      cp .gitpod/sites.php docroot/sites/local.sites.php &&
      composer install --no-interaction &&
      rm -rf docroot/*/custom/* &&
      composer install --prefer-source --no-interaction &&
      blt blt:telemetry:disable --no-interaction &&
      cp .gitpod/gitpod.settings.php docroot/sites/settings/local.settings.php &&
      blt settings &&
      mysql -u root -e 'CREATE DATABASE IF NOT EXISTS drupal_default; CREATE DATABASE IF NOT EXISTS drupal' &&
      blt sws:keys &&
      mysql -e 'SET GLOBAL max_allowed_packet=67108864;' &&
      if [[ ! -z $SSH_PRIVATE_KEY ]]; then
        blt drupal:sync --site=hs_colorful -n &&
        drush sql-sync @hs_colorful.local @self -y
      else
        blt drupal:install --no-interaction
      fi
    command: >
      git config core.fileMode false &&
      apache2ctl restart &&
      gp ports await 8001 &&
      drush uli &&
      drush uli | xargs gp preview --external
