ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: open-preview
image:
  file: .gitpod/Dockerfile
tasks:
  - before: .gitpod/before.sh
    init: .gitpod/init.sh
    command: |
      vendor/bin/blt blt:telemetry:disable -n
      apache2ctl restart
      .gitpod/ssh_key.ssh
      eval `ssh-agent -s`
      ssh-add /workspace/.ssh/id_rsa
      blt sws:keys
      blt source:build:simplesamlphp-config
#github:
#  prebuilds:
#    # enable for the master/default branch (defaults to true)
#    master: true
#    # enable for all branches in this repo (defaults to false)
#    branches: false
#    # enable for pull requests coming from this repo (defaults to true)
#    pullRequests: true
#    # enable for pull requests coming from forks (defaults to false)
#    pullRequestsFromForks: false
#    # add a check to pull requests (defaults to true)
#    addCheck: true
#    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
#    addComment: false
#    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
#    addBadge: false
#    # add a label once the prebuild is ready to pull requests (defaults to false)
#    addLabel: gitpod
