name: suhumsci
recipe: drupal8
config:
  webroot: docroot
  php: '7.1'
proxy:
  appserver:
    - swshumsci.suhumsci.loc
    - archaeology.suhumsci.loc
#   solr:
#     - solr.mrcblt.sws:8983
services:
  appserver:
    ssl: true
    extras:
      - "apt-get update"
      - "ln -s /app/vendor/bin/blt /usr/bin/blt"
  archaeology:
    type: mysql:5.7
    creds:
      user: drupal8
      password: drupal8
      database: archaeology

  # solr:
  #   type: solr:5.5
  #   portforward: true
  #   core: project
  #   config:
  #     conf: solrconf
  # memcache:
  #   type: memcached:1.5
  #   mem: 128
  #   portforward: true

tooling:
  blt:
    service: appserver
    cmd: /usr/bin/blt
  git:
    service: appserver
