name: arch
recipe: drupal8
config:
  webroot: docroot
  php: '7.1'
services:
  appserver:
    ssl: true
    extras:
      - apt-get update
      - ln -s /app/vendor/bin/blt /usr/bin/blt
  database:
    type: 'mysql:5.7'
tooling:
  blt:
    service: appserver
    cmd: /usr/bin/blt
  git:
    service: appserver
