<?php

/**
 * @file
 * mrc_news.module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_entity_presave().
 */
function mrc_news_entity_presave(EntityInterface $entity) {
  if ($entity instanceof Node && $entity->bundle() == 'stanford_news_item') {
    if ($entity->hasField('field_s_news_link')) {
      /** @var \Drupal\Core\Field\FieldItemList $field */
      $field = $entity->get('field_s_news_link');
      if (!$field->count()) {
        $entity->set('rh_action', 'display_page');
      }
      else {
        $entity->set('rh_action', 'bundle_default');
      }
    }
  }
}
