hs_entities.hs_entities_type.*:
  type: config_entity
  label: 'H&amp;S Entities type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
