<?php

/**
 * @file
 * Contains hs_migrate.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\config_pages\ConfigPagesInterface;

/**
 * Implements hook_help().
 */
function hs_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_migrate module.
    case 'help.page.hs_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds more functionality to migrate and migrate plus modules') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migrate_process_info_alter().
 */
function hs_migrate_migrate_process_info_alter(array &$definitions) {
  // Change the class we use for the subprocess functionality to cast xml
  // objects as arrays.
  $definitions['sub_process']['class'] = '\Drupal\hs_migrate\Plugin\migrate\process\SubProcess';
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function hs_migrate_config_pages_presave(ConfigPagesInterface $config_page) {
  if ($config_page->id() == 'drupal_7_importers') {
    Cache::invalidateTags(['migration_plugins']);
  }
}
