saml_attribute: eduPersonEnttitlement
workgroup_api_url: 'https://workgroupsvc.stanford.edu/v1/workgroups'
use_workgroup_api: false
hide_local_login: true
workgroup_api_cert: '/mnt/gfs/swshumsci.dev/nobackup/apikeys/saml/workgroup_api.cert'
workgroup_api_key: '/mnt/gfs/swshumsci.dev/nobackup/apikeys/saml/workgroup_api.key'
restriction: all
whitelist_groups: {  }
whitelist_users: {  }
_core:
  default_config_hash: Xm4MNDvuD7BJ089bXHgqkS7_mOjVgGxnekzaeYLwW7k
