imports:
  - behat.yml

default:
  suites:
    default:
      contexts:
        - Drupal\FeatureContext
        - Drupal\FeatureMinkContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - StanfordBehat\DrupalExtension\Context\SwsContext
        - StanfordBehat\DrupalExtension\Context\SwsMinkContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://localhost
      sessions:
        default:
          goutte: ~
        javascript:
          selenium2:
            browser: chrome
            wd_host: http://localhost:4444/wd/hub
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: 'self'
        binary: '/var/www/html/vendor/bin/drush'
      drupal:
        drupal_root: '/var/www/html/docroot'
      region_map:
        header: "#header"
        content: "div#main-content, .region-content"
        footer: "#footer"
        global_footer: "#footer__global-footer"
      selectors:
        message_selector: '.messages'
        error_message_selector: '.messages.messages--error'
        success_message_selector: '.messages.messages--status'
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: /var/www/html/artifacts

