<?php

/**
 * @file
 * hs_field_helpers.module
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function hs_field_helpers_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\WidgetBaseInterface $widget */
  $widget = $context['widget'];

  // To simulate the same field functionality as we had in D7, we need to
  // add a checkbox and validation handlers.
  if ($widget->getBaseId() == 'daterange_datelist') {

    // Adds wrappers so we can easily find the parts with jQuery.
    $element['value']['#prefix'] = '<div class="start-date">';
    $element['value']['#suffix'] = '</div>';
    $element['end_value']['#prefix'] = '<div class="end-date">';
    $element['end_value']['#suffix'] = '</div>';

    $show_end = FALSE;

    // Compare start and end dates to determine default checkbox value.
    if (!empty($element['value']['#default_value']) && !empty($element['end_value']['#default_value'])) {
      /** @var \DateInterval $diff */
      $diff = $element['value']['#default_value']->diff($element['end_value']['#default_value']);
      $show_end = (bool) (int) $diff->format('%Y%M%D%H%I%S');
    }

    $element['show_end'] = [
      '#type' => 'checkbox',
      '#title' => t('Show End Date'),
      '#default_value' => $show_end,
      '#attributes' => ['class' => ['show-end-date']],
    ];

    $element['#attached']['library'][] = 'hs_field_helpers/admin';
    array_unshift($element['#element_validate'], 'hs_field_helpers_node_validate_date');
  }

}

/**
 * Validation for event dates in nodes form.
 */
function hs_field_helpers_node_validate_date(array &$element, FormStateInterface $form_state) {
  $date = $form_state->getValue('field_hs_event_date');

  // If the start value is populated but end is empty, copy the start date
  // to the end date to pass validation.
  if (!empty($date[0]['value']) && (!$date[0]['show_end'] || empty($date[0]['end_value']))) {
    $date[0]['end_value'] = $date[0]['value'];
    $element['end_value']['#value']['object'] = $date[0]['end_value'];

    /** @var \Drupal\Core\Datetime\DrupalDateTime $date */
    $form_state->setValue('field_hs_event_date', $date);
  }
}
