<?php

/**
 * @file
 * hs_layouts.module
 */

use Drupal\Component\Utility\Html;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function hs_layouts_plugin_filter_layout__layout_builder_alter(&$definitions, &$extra, &$consumer) {
  /** @var \Drupal\Core\Layout\LayoutDefinition $definition */
  foreach ($definitions as $id => $definition) {
    if ($definition->getProvider() !== 'hs_layouts') {
      unset($definitions[$id]);
    }
  }
}

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function hs_layouts_plugin_filter_block__layout_builder_alter(&$definitions, &$extra) {
  foreach ($definitions as $id => &$definition) {
    if (strpos($id, 'views_exposed_filter_block') !== FALSE) {
      $view_block = str_replace('views_exposed_filter_block:', 'views_block:', $id);
      if (isset($definitions[$view_block])) {
        $definition['category'] = $definitions[$view_block]['category'];
        $definition['admin_label'] = t('@view: @display <span class="view-form">Exposed form</span>', $definitions[$view_block]['admin_label']->getArguments());
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_layouts_preprocess_container(&$variables) {
  if (!empty($variables['element']['layout-section'])) {
    // Add styles to the layout builder admin configuration.
    $variables['#attached']['library'][] = 'hs_layouts/layout_builder_admin';
  }
}

/**
 * Implements hook_preprocess_preprocess_pattern_spotlight().
 */
// function hs_layouts_preprocess_pattern_spotlight(&$variables) {
//   $paragraph = $variables['context']->getProperty('entity');
//   if (
//     $paragraph instanceof ParagraphInterface &&
//     $paragraph->hasField('field_hs_spotlight_bg') &&
//     $paragraph->get('field_hs_spotlight_bg')->count()
//   ) {
//     $bgValue = $paragraph->get('field_hs_spotlight_bg')->getString();
//     $variables['attributes']->addClass(Html::cleanCssIdentifier($bgValue));
//   }
// }

/**
 * Implements hook_preprocess_preprocess_pattern_accordion().
 */
// function hs_layouts_preprocess_pattern_accordion(&$variables) {
//   $paragraph = $variables['context']->getProperty('entity');
//   if (
//     $paragraph instanceof ParagraphInterface &&
//     $paragraph->hasField('field_hs_accord_expcol') &&
//     $paragraph->get('field_hs_accord_expcol')->first()->getValue()['value'] === '1'
//   ) {
//     $variables['attributes']->addClass('hb-accordion_toggle-all');
//   }
// }
