_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'system.theme:default'
  - '~block.block.su_humsci_admin_*'
  - '~block.block.seven_*'
  - '~block.block.humsci_basic_*'
  - '~block.block.humsci_colorful_*'
  - '~block.block.humsci_traditional_*'
  - 'block.block.*'
  - system.site
  - hs_capx.settings
  - 'migrate_plus.migration.*:status'
  - 'migrate_plus.migration.custm*'
enable_export_filtering: true
