_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'system.theme:default'
  - system.site
  - hs_capx.settings
  - 'migrate_plus.migration.*:status'
enable_export_filtering: true
