_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'system.theme:default'
  - 'block.block.*'
  - '~block.block.su_humsci_theme_*'
  - '~block.block.su_humsci_admin_*'
  - '~block.block.seven_*'
  - ~block.block.humsci_basic_global_message
  - ~block.block.humsci_colorful_global_message
  - ~block.block.humsci_traditional_global_message
  - system.site
  - hs_capx.settings
  - 'migrate_plus.migration.*:status'
  - 'migrate_plus.migration.custm*'
enable_export_filtering: true
