adding: {  }
removing:
  ignored_config_entities:
    - '*custm*'
    - 'block.block.*'
    - 'config_split.config_split.not_live:status'
    - content_access.settings
    - 'core.entity_form_display.node.hs_*'
    - core.entity_view_display.media.image.hs_colorbox
    - 'core.entity_view_display.node.hs_*'
    - core.entity_view_display.paragraph.stanford_gallery.default
    - 'core.extension:theme'
    - 'domain_301_redirect.settings:domain'
    - 'domain_301_redirect.settings:enabled'
    - 'domain_registration.settings:pattern'
    - 'field.field.node.hs_basic_page.field_hs_page_components:settings.handler_settings'
    - 'field.field.node.hs_basic_page.field_hs_page_hero:settings.handler_settings'
    - 'field.field.node.hs_private_page.field_hs_priv_page_components:settings.handler_settings'
    - 'field.field.paragraph.hs_row.field_hs_row_components:settings.handler_settings'
    - 'google_analytics.settings:account'
    - 'google_analytics.settings:cross_domains'
    - 'google_analytics.settings:domain_mode'
    - 'google_analytics.settings:premium'
    - 'google_analytics.settings:track'
    - 'google_analytics.settings:visibility'
    - 'menu_position.menu_position_rule.*'
    - 'migrate_plus.migration.custm*'
    - 'samlauth.authentication:map_users_roles'
    - stanford_samlauth.settings
    - 'user.role.*:permissions'
    - 'user.settings:register'
    - 'views.view.hs_*:status'
    - '~block.block.claro*'
    - '~block.block.gin*'
    - '~block.block.humsci_*'
    - '~block.block.su_humsci_*'
    - ~gin.settings
    - ~su_humsci_gin_admin.settings
