adding:
  ignored_config_entities:
    - '~block.block.seven_*'
  enable_export_filtering: true
removing:
  ignored_config_entities:
    - 'asset_injector.*'
    - 'config_split.config_split.not_live:status'
    - content_access.settings
    - 'core.entity_form_display.media.*'
    - 'core.entity_form_display.node.hs_*'
    - core.entity_view_display.media.image.hs_colorbox
    - 'core.entity_view_display.node.hs_*'
    - core.entity_view_display.paragraph.stanford_gallery.default
    - 'core.extension:theme'
    - 'domain_301_redirect.settings:domain'
    - 'domain_301_redirect.settings:enabled'
    - 'field.field.node.hs_basic_page.field_hs_page_components:settings.handler_settings'
    - 'field.field.node.hs_basic_page.field_hs_page_hero:settings.handler_settings'
    - 'field.field.node.hs_private_page.field_hs_priv_page_components:settings.handler_settings'
    - 'google_analytics.settings:account'
    - 'google_analytics.settings:cross_domains'
    - 'google_analytics.settings:domain_mode'
    - 'google_analytics.settings:premium'
    - 'google_analytics.settings:track'
    - 'google_analytics.settings:visibility'
    - 'menu_position.menu_position_rule.*'
    - 'samlauth.authentication:map_users_roles'
    - 'single_content_sync.settings:allowed_entity_types.node'
    - stanford_samlauth.settings
    - 'user.role.*:permissions'
    - 'user.role.custm*'
    - 'user.settings:register'
    - 'views.view.hs_*:status'
