ignored_config_entities:
  - 'system.theme:default'
  - 'core.extension:theme'
  - 'block.block.*'
  - '~block.block.seven*'
  - '~block.block.su_humsci_admin*'
  - '~block.block.su_humsci_theme*'
  - '~block.block.humsci_basic_*'
  - '~block.block.humsci_colorful_*'
  - '~block.block.humsci_traditional_*'
  - system.site
  - hs_capx.settings
  - 'migrate_plus.migration.*:status'
  - 'migrate_plus.migration.custm*'
enable_export_filtering: true
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
