ignored_config_entities:
  - 'system.theme:default'
  - 'core.extension:theme'
  - 'block.block.*'
  - '~block.block.su_humsci_theme_*'
  - '~block.block.su_humsci_admin_*'
  - '~block.block.seven_*'
  - 'bugherd_api.settings:project_key'
  - system.site
  - hs_capx.settings
enable_export_filtering: '1'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
