ignored_config_entities:
  - 'system.theme:default'
  - 'core.extension:theme'
  - 'block.block.*'
  - '~block.block.su_humsci_theme_*'
  - '~block.block.su_humsci_admin_*'
  - '~block.block.seven_*'
  - system.site
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
