<?php

/**
 * @file
 * mrc_visitor.mdoule
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node ;

/**
 * Implements hook_field_widget_form_alter().
 */
function mrc_visitor_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Change form to be a year range instead of a single year.
  if ($context['items']->getName() == 'field_s_visitor_year_visited') {
    foreach ($element['value']['#options'] as &$option) {
      $option = $option - 1 . ' - ' . $option;
    }

    krsort($element['value']['#options']);
  }
}

/**
 * Implements hook_entity_presave().
 */
function mrc_visitor_entity_presave(EntityInterface $entity) {
  if ($entity instanceof Node && $entity->bundle() == 'stanford_visitor') {
    if (!$entity->getFieldDefinition('field_mrc_image') || !$entity->get('field_mrc_image')
        ->isEmpty()) {
      return;
    }
    $config = \Drupal::config('mrc_visitor.default_image');

    if ($media = \Drupal::entityTypeManager()
      ->getStorage('media')
      ->load($config->get('mid'))) {

      // Set the default image on visitor content.
      $entity->set('field_mrc_image', $media->id());
    }
  }
}
