status: 2
pattern: '[node:field_hs_person_first_name] [node:field_hs_person_middle_name] [node:field_hs_person_last_name]'
php: false
dependencies:
  config:
    - node.type.hs_person
_core:
  default_config_hash: b2jiaR58rJ-PS422CdCpuf7ju4fDDk7ALAM1245N7gk
