roles:
  anonymous:
    theme: ''
    admin_theme: ''
    weight: '3'
  authenticated:
    theme: ''
    admin_theme: ''
    weight: '5'
  administrator:
    theme: ''
    admin_theme: ''
    weight: '7'
  contributor:
    theme: ''
    admin_theme: ''
    weight: '9'
  site_manager:
    theme: ''
    admin_theme: ''
    weight: '11'
  seven_admin_theme_user:
    theme: ''
    admin_theme: seven
    weight: '1'
