features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
browser_sync:
  enabled: 0
  host: ''
  port: ''
ie_enabled: 0
ie_enabled_versions:
  ie8: 0
  ie9: 0
humsci_site_styles: archaeology
