<?php

/**
 * @file
 * Contains hs_views_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\hs_views_helper\Plugin\views\query\Sql as HsViewsSql;
use Drupal\Core\Cache\Cache;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\node\NodeInterface;
use Drupal\views\Plugin\views\filter\Bundle;

/**
 * Implements hook_help().
 */
function hs_views_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_views_helper module.
    case 'help.page.hs_views_helper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides additional plugins and support for views module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_post_render().
 *
 * Views render arrays contain a cache tag "node_list". This cache tag is
 * cleared every time ANY node is created, edited or deleted. When this happens
 * every view on the site gets its cache flushed. This causes poor performance
 * since a view would get flushed even if it has no relation to that node. To
 * assist in cache tags, we create a custom cache tag based on the node type
 * filter on the view. Its a small improvement but will have huge impact in
 * keeping cached renders much longer.
 *
 * @see hs_views_helper_node_presave()
 */
function hs_views_helper_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  if (
    isset($view->filter['type']) &&
    $view->filter['type'] instanceof Bundle &&
    $view->filter['type']->getEntityType() == 'node' &&
    $view->filter['type']->value
  ) {
    $node_list_position = array_search('node_list', $output['#cache']['tags']);
    unset($output['#cache']['tags'][$node_list_position]);
    foreach ($view->filter['type']->value as $node_type) {
      $output['#cache']['tags'][] = "node_list:$node_type";
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @see hs_views_helper_views_post_render()
 */
function hs_views_helper_node_presave(NodeInterface $entity) {
  Cache::invalidateTags(["node_list:{$entity->bundle()}"]);
}

/**
 * Implements hook_views_plugins_style_alter().
 */
function hs_views_helper_views_plugins_style_alter(array &$plugins) {
  $plugins['serializer']['class'] = '\Drupal\hs_views_helper\Plugin\views\style\HumsciSerializer';
}

/**
 * Implements hook_views_plugins_query_alter().
 */
function hs_views_helper_views_plugins_query_alter(array &$plugins) {
  $plugins['views_query']['class'] = '\Drupal\hs_views_helper\Plugin\views\query\Sql';
}

/**
 * Implements hook_views_query_alter().
 */
function hs_views_helper_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($query instanceof HsViewsSql) {
    $query->alterQuery($view);
  }
}

/**
 * Implements hook_views_data_alter().
 */
function hs_views_helper_views_data_alter(array &$data) {
  /** @var \Drupal\field\Entity\FieldStorageConfig $field_storage */
  foreach (FieldStorageConfig::loadMultiple() as $field_storage) {
    if ($field_storage->getType() != 'datetime') {
      continue;
    }
    $entity_type = $field_storage->getTargetEntityTypeId();
    $field_name = $field_storage->getName();

    // Change the filter id to our custom filter. This will give us an optional
    // exception window for academic calendars.
    $value_data = &$data["{$entity_type}__{$field_name}"]["{$field_name}_value"];
    $value_data['filter']['id'] = 'academic_datetime';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hs_views_helper_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  if (empty($form['actions']['reset'])) {
    return;
  }

  // Ajax blocks using the module views_block_filter_block do not display the
  // "Reset" button after the form has been submitted. So we are going to change
  // the access and apply some javascript to help keep the ajaxy feel.
  $form['actions']['reset']['#access'] = TRUE;
  $form['#attached']['library'][] = 'hs_views_helper/views_reset';
}

/**
 * Implements hook_preprocess_views_view_pattern().
 */
function hs_views_helper_preprocess_views_view_pattern(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  $pattern = $view->style_plugin->options['pattern'];
  $variables['pattern'] = $pattern;
}
