<?php

/**
 * @file
 * hs_courses.module
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\hs_entities\HsEntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function hs_courses_hs_entity_view_alter(array &$build, HsEntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() != 'course_collections__instructor') {
    return;
  }
  if ($entity->get('field_instructor_person')->count()) {
    unset($build['label']);
    return;
  }

  /** @var \Drupal\Core\Field\FieldItemList $instructor_role_list */
  $instructor_role_list = $entity->get('field_instructor_role');
  if ($instructor_role_list->count()) {
    $build['label'][0]['#context']['value'] .= ' (' . $instructor_role_list->getString() . ')';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Append the instructor's role onto the link title.
 */
function hs_courses_preprocess_field__field_instructor_person(&$variables) {
  /** @var \Drupal\Core\Field\FieldItemList $instructor_role_list */
  $instructor_role_list = $variables['element']['#object']->get('field_instructor_role');
  if ($instructor_role_list->count() && !empty($variables['items'][0]['content']['#title'])) {
    $variables['items'][0]['content']['#title'] .= ' (' . $instructor_role_list->getString() . ')';
  }
}
