block.settings.hs_blocks_social_media_block:
  type: block_settings
  label: 'Social Media Block Configuration'
  mapping:
    icon_size:
      type: string
      label: 'Icon Size'
    layout:
      type: string
      label: String
    text_above:
      type: text_format
      label: 'Text Above'
    text_below:
      type: text_format
      label: 'Text Below'
    links:
      type: sequence
      label: Links
      sequence:
        link_url:
          type: uri
          label: URL
        link_title:
          type: string
          label: Title
        _weight:
          type: integer
          label: Weight
