name: suhumsci
recipe: drupal8
config:
  webroot: docroot
  php: '7.4'
proxy:
  appserver:
    - swshumsci.suhumsci.loc
    - archaeology.suhumsci.loc
    - artexhibitions.suhumsci.loc
    - buddhiststudies.suhumsci.loc
    - dsresearch.suhumsci.loc
    - duboislab.suhumsci.loc
    - economics.suhumsci.loc
    - francestanford.suhumsci.loc
    - insidehs.sushumsci.loc
    - it-humsci.suhumsci.loc
    - lowe.suhumsci.loc
    - mathematics.suhumsci.loc
    - mcs.suhumsci.loc
    - mrc.suhumsci.loc
    - philit.suhumsci.loc
    - popstudies.suhumsci.loc
    - shenlab.suhumsci.loc
    - sparkbox-sandbox.suhumsci.loc
    - swshumsci-sandbox.suhumsci.loc
    - symsys.suhumsci.loc
services:
  appserver:
    ssl: true
  database: # Override the database that comes in the drupal8
    creds:  # recipe and use it for the /sites/default site.
      user: drupal
      password: drupal
      database: sparkbox_sandbox
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  # archaeology:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: archaeology
  # artexhibitions:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: artexhibitions
  # buddhiststudies:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: buddhiststudies
  # dsresearch:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: dsresearch
  # duboislab:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: duboislab
  # economics:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: economics
  # francestanford:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: francestanford
  # ithumsci:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: it_humsci
  # lowe:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: lowe
  # mathematics:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: mathematics
  # mcs:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: mcs
  # mrc:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: mrc
  # philit:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: philit
  # shenlab:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: shenlab
  # sparkbox_sandbox:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: sparkbox_sandbox
  # swshumsci_sandbox:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: swshumsci_sandbox
  # symsys:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal
  #     password: drupal
  #     database: symsys
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  git:
    service: appserver
