<?php

/**
 * @file
 * Contains hs_revision_cleanup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hs_revision_cleanup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_revision_cleanup module.
    case 'help.page.hs_revision_cleanup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Set limitations on how many revisions are kept for particular entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function hs_revision_cleanup_cron() {
  \Drupal::service('hs_revision_cleanup')->deleteRevisions();
}
