<?php

/**
 * @file
 * Contains hs_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function hs_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_blocks module.
    case 'help.page.hs_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Humsci Blocks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hs_blocks_theme($existing, $type, $theme, $path) {
  return [
    'hs_blocks_login' => [
      'template' => 'block--hs-login',
      'variables' => ['preface' => NULL, 'link' => NULL, 'postface' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_blocks_preprocess_block__block_content(&$variables) {
  /** @var \Drupal\block_content\Entity\BlockContent $block_entity */
  $block_entity = $variables['content']['#block_content'];
  if (
    $block_entity->hasField('field_hs_block_hide_title') &&
    $block_entity->get('field_hs_block_hide_title')->getString()
  ) {
    $variables['label'] = '';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hs_blocks_form_layout_builder_update_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  unset($form['settings']['label_display']);
  $form['settings']['formatter']['label']['#options']['above_h2'] = t('Above H2');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hs_blocks_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  unset($form['settings']['label_display']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_blocks_preprocess_block__layout_builder(&$variables) {
  if(!isset($variables['configuration']['formatter'])){
    dpm($variables);
  }
  if ($variables['configuration']['formatter']['label'] == 'above_h2') {
    $variables['content']['#label_display'] = 'hidden';
    $variables['label'] = $variables['configuration']['label'];
  }
}
