<?php

/**
 * @file
 * humsci_default_content.module
 */

use Drupal\Core\Serialization\Yaml;

/**
 * Update the info file with the default content uuids.
 */
function _humsci_default_content_update_info() {
  $info = Yaml::decode(file_get_contents(__DIR__ . '/humsci_default_content.info.yml'));
  foreach (glob(__DIR__ . '/content/*') as $directory) {
    $entity_type = basename($directory);
    $info['default_content'][$entity_type] = [];

    foreach (glob("$directory/*.json") as $file) {
      $info['default_content'][$entity_type][] = basename($file, '.json');
    }
    asort($info['default_content'][$entity_type]);
  }
  file_put_contents(__DIR__ . '/humsci_default_content.info.yml', Yaml::encode($info));
}
