<?php

/**
 * @file
 * hs_courses_importer.module
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_cron().
 */
function hs_courses_importer_cron() {
  $entities = \Drupal::entityTypeManager()
    ->getStorage('course_collections')
    ->loadMultiple();
  foreach ($entities as $entity) {
    $entity->delete();
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function hs_courses_importer_node_delete(NodeInterface $entity) {

}
