views.filter.academic_date:
  type: views.filter.date
  label: 'Academic Date'
  mapping:
    exception:
      type: views.filters.exception
      label: 'Exception'

views.filter_value.academic_date:
  type: views.filter_value.date
  label: 'Academic Date'
  mapping:
    exception:
      type: views.filters.exception
      label: 'Exception'

views.filters.exception:
  type: mapping
  label: 'Exception Settings'
  mapping:
    exception:
      type: boolean
      label: 'Use Exception'
    start_month:
      type: integer
      label: 'Exception Start Month'
    start_day:
      type: integer
      label: 'Exception Start Day'
    end_month:
      type: integer
      label: 'Exception End Month'
    end_day:
      type: integer
      label: 'Exception End Day'
    value:
      type: string
      label: 'Exception Value'
    min:
      type: string
      label: 'Exception Minimum'
    max:
      type: string
      label: 'Exception Maximum'
