<?php

/**
 * @file
 * hs_editorial.module
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_presave().
 */
function hs_editorial_node_presave(NodeInterface $node) {
  // Users with the 'Preparer' role are not allowed to publish new content.
  // Override the default publishing status set within the content types.
  if ($node->isNew() && in_array('preparer', \Drupal::currentUser()->getRoles())) {
    $node->setUnpublished();
  }
}

/**
 * Implements hook_node_access().
 */
function hs_editorial_node_access(NodeInterface $node, $op, AccountInterface $account) {
  // Users with the 'Preparer' role are not allowed to edit published content.
  // This closes a gap with the currently available permissions where edit does
  // not differentiate between published and unpublished nodes.
  if ($op === 'update'
    && $node->isPublished()
    && in_array('preparer', $account->getRoles())) {
    return AccessResult::forbidden()->addCacheableDependency($node);
  }
  // Default response should return neutral, letting other access checks decide.
  return AccessResult::neutral();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hs_editorial_form_node_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // Users with the 'Preparer' role are allowed to add or modify a menu link
  // when on the node form.
  if (in_array('preparer', \Drupal::currentUser()->getRoles())) {
    $form['field_menulink']['#access'] = TRUE;
  }
}
