core.entity_view_display.*.*.*.third_party.mrc_ds_blocks:
  type: sequence
  label: 'Blocks to display on entity display mode.'
  sequence:
    - type: mapping
      label: A block
      mapping:
        config:
          type: array
          label: 'The block display configurations.'
        blockId:
          type: string
          label: 'The machine name of the block'
        parent_name:
          type: string
          label: 'The parent group of this block'
        weight:
          type: integer
          label: 'The weight of the block'
