name: 'H&S Config Read Only'
description: 'Modify the Config Read Only to blacklist specific config'
core_version_requirement: ^9.4 || ^10
type: module
version: 8.2.7
package: 'Humanities & Sciences'
dependencies:
  - config_readonly
  - config_filter
