name: 'H&S Config Read Only'
description: 'Modify the Config Read Only to blacklist specific config'
core: 8.x
type: module
version: 8.0.11
package: 'Humanities & Sciences'
dependencies:
  - config_readonly
  - config_filter
