services:
  hs_config_readonly.form_subscribe:
    class: Drupal\hs_config_readonly\EventSubscriber\ConfigReadOnlyEventSubscriber
    decorates: config_readonly_form_subscriber
    public: false
    arguments: ['@module_handler', '@config.factory', '@config.storage.staging', '@plugin.manager.config_filter', '@entity_type.manager']
