<?php

/**
 * @file
 * hs_view.install
 */

/**
 * Implements hook_install().
 */
function hs_view_install() {
  /** @var \Drupal\Core\Extension\ModuleInstaller $module_installer */
  $module_installer = \Drupal::service('module_installer');
  try {
    $module_installer->install(['hs_view_display']);
  }
  catch (Exception $e) {
    \Drupal::messenger()
      ->addError(t('Unable to set initial display settings for View Paragraph'));
  }

}
