services:

  # What to call the service hosting the site.
  suhumsci:

    # Use PHP 8 with Apache
    image: pookmish/drupal8ci:tugboat

    # Set this as the default service. This does a few things
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true

    # Wait until the mysql service is done building
    depends: mysql
    aliases:
      - hs-colorful
      - hs-traditional
      - english
      - history
      - west

    # A set of commands to run while building this service
    commands:

      # Commands that set up the basic preview infrastructure
      init:
        # Install Node.js system-wide based on .nvmrc major version for consistent builds
        - export NODE_VERSION=$(cat .nvmrc | cut -d. -f1) && curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - && apt-get install -y nodejs
        # Symlink the tugboat directory to the docker image expected path.
        - rm -rf /var/www/localhost
        - ln -snf ${TUGBOAT_ROOT} /var/www/localhost
        - ln -s docroot htdocs

        # Install/update packages managed by composer, including drush
        - rm -rf vendor
        - composer install --no-ansi

        # Init the settings files.
        - blt blt:init:settings
      update:
        - rm -rf vendor
        - composer install --no-ansi
        # Sync to hs_colorful, hs_colorful database & files and create user.
        - blt drupal:sync --site=hs_colorful -n
        - drush @hs_colorful.local user:create tugboat --password=pushcar || true
        - drush @hs_colorful.local user:role:add administrator tugboat || true

        - blt drupal:sync --site=hs_traditional -n
        - drush @hs_traditional.local user:create tugboat --password=pushcar || true
        - drush @hs_traditional.local user:role:add administrator tugboat || true

        # Sync to english, history, and west database & files, does not create a user.
        - blt drupal:sync --site=english -n
        - blt drupal:sync --site=history -n
        - blt drupal:sync --site=west -n

        - chown -R www-data:www-data ${TUGBOAT_ROOT}/docroot/sites/*/files
      build:
        - rm -rf vendor
        - composer install --no-ansi

        - drush @hs_colorful.local cr
        - drush @hs_colorful.local eval '\Drupal::moduleHandler()->loadInclude("user", "install");user_update_10000();'
        - blt drupal:update --site=hs_colorful

        - drush @hs_traditional.local cr
        - drush @hs_traditional.local eval '\Drupal::moduleHandler()->loadInclude("user", "install");user_update_10000();'
        - blt drupal:update --site=hs_traditional

        - drush @english.local cr
        - drush @english.local eval '\Drupal::moduleHandler()->loadInclude("user", "install");user_update_10000();'
        - blt drupal:update --site=english

        - drush @history.local cr
        - drush @history.local eval '\Drupal::moduleHandler()->loadInclude("user", "install");user_update_10000();'
        - blt drupal:update --site=history

        - drush @west.local cr
        - drush @west.local eval '\Drupal::moduleHandler()->loadInclude("user", "install");user_update_10000();'
        - blt drupal:update --site=west

        - npm run theme-build

    # Collection of urls to compare visual results.
    urls:
      hs-colorful:
        - /
        - /mixed-pages/mixed-page-raised-cards
        - /mixed-page-wells-raised-cards-full-width
        - /mixed-pages/mixed-page-wells-raised-cards-full-width-sidebar
        - /default-views/news
        - /default-views/events
        - /default-views/people
        - /components/hero-images-main-region/banner-images-partial-overlay-and-text
        - /components/hero-images-main-region/banner-images-text-box
        - /components/hero-images-full-width-region-and-main-region/tall-spotlights-classic
        - /components/text-area-typography
      hs-traditional:
        - /
        - /mixed-pages/mixed-page-raised-cards
        - /mixed-page-wells-raised-cards-full-width
        - /mixed-pages/mixed-page-wells-raised-cards-full-width-sidebar
        - /default-views/news
        - /default-views/events
        - /default-views/people
        - /components/hero-images-main-region/banner-images-partial-overlay-and-text
        - /components/hero-images-main-region/banner-images-text-box
        - /components/hero-images-full-width-region-and-main-region/tall-spotlights-classic
        - /components/text-area-typography
  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:

    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mysql:5
    commands:
      init:
        # Increase the allowed packet size to 512MB.
        - mysql -e "SET GLOBAL max_allowed_packet=536870912;"
        # Ensure this packet size persists even if MySQL restarts.
        - echo "max_allowed_packet=536870912" >> /etc/mysql/conf.d/tugboat.cnf
      update:
        # Delete and recreate the database for each site.
        # - mysql -e "DROP DATABASE IF EXISTS hs_colorful; CREATE DATABASE hs_colorful;"
        # - mysql -e "DROP DATABASE IF EXISTS hs_traditional; CREATE DATABASE hs_traditional;"
        # - mysql -e "DROP DATABASE IF EXISTS english; CREATE DATABASE english;"
        # - mysql -e "DROP DATABASE IF EXISTS history; CREATE DATABASE history;"
        # - mysql -e "DROP DATABASE IF EXISTS west; CREATE DATABASE west;"

        # Give the tugboat user access to the new databases.
        - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'tugboat'; FLUSH PRIVILEGES;"
