services:

  # What to call the service hosting the site.
  suhumsci:

    # Use PHP 7.2 with Apache
    image: pookmish/tugboat:latest

    # Set this as the default service. This does a few things
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true

    # Wait until the mysql service is done building
    depends: mysql
    aliases:
      - hs-colorful
      - hs-traditional

    # A set of commands to run while building this service
    commands:

      # Commands that set up the basic preview infrastructure
      init:
        # Symlink the tugboat directory to the docker image expected path.
        - rm -rf /var/www/localhost
        - ln -snf ${TUGBOAT_ROOT} /var/www/localhost
        - ln -s docroot htdocs

        # Install/update packages managed by composer, including drush
        - composer install --no-ansi
        - blt blt:telemetry:disable --no-interaction

        # Init the settings files.
        - blt blt:init:settings

        # Copy SimpleSAMLphp configuration to prevent annoying errors.
        - blt source:build:simplesamlphp-config

        # Sync to hs_colorful and symlink the files directory.
        - blt drupal:sync --site=hs_colorful
        - blt drupal:sync:files --site=hs_colorful
        - blt drupal:sync --site=hs_traditional
        - blt drupal:sync:files --site=hs_traditional
        - chown -R www-data:www-data ${TUGBOAT_ROOT}/docroot/sites/*/files
        - drush user:create tugboat --password=tugboat
        - drush user:role:add administrator tugboat
      build:
        - composer install --no-ansi
        - blt drupal:update
        - drush pmu simplesamlphp_auth -y

    # Collection of urls to compare visual results.
    urls:
      - /

  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:

    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mysql:5
