name: 'HS Config Partial'
type: module
description: 'Prevents config deletions during config import (mimics partial import).'
package: 'Humanities & Sciences'
core_version_requirement: ^10.3 || ^11
dependencies: []
