hs_config_readonly.settings:
  type: config_object
  label: 'HS Config Readonly Settings'
  mapping:
    excluded_modules:
      type: sequence
      label: 'Excluded Modules'
    form_ids:
      type: sequence
      label: 'Always Blocked Form Ids'

