<?php

/**
 * @file
 * Custom functions for dashboard-related views and tasks.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\shortcut\Entity\Shortcut;
use Drupal\user\UserInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

// These roles don't get a full dashboard, instead they get just a "My Content"
// page, and a limited set of shortcuts.
const HS_DASHBOARD_LOW_LEVEL_ROLES = ['author', 'preparer'];

/**
 * Implements hook_theme().
 */
function hs_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'hs_importers_info' => [
      'variables' => ['importers' => []],
    ],
    'hs_theme_info_block' => [
      'variables' => [
        'theme_name' => NULL,
        'color_pairing' => NULL,
        'animation_enhancements' => NULL,
        'help_text' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_query_alter().
 */
function hs_dashboard_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Finds duplicated published person nodes.
  if ($view->id() === 'duplicate_people' && in_array('node_field_data', $view->getBaseTables())) {
    $sub_query = \Drupal::database()->select('node_field_data', 'sub_query')
      ->fields('sub_query', ['title'])
      ->condition('sub_query.type', 'person')
      ->condition('sub_query.status', '1')
      ->groupBy('sub_query.title')
      ->having('COUNT(sub_query.title) > 1');

    /** @var Drupal\hs_views_helper\Plugin\views\query\Sql $query */
    $query->addWhereExpression(
      NULL,
      'node_field_data.title IN (' . $sub_query->__toString() . ')'
    );
  }
}

/**
 * Implements hook_views_data_alter().
 */
function hs_dashboard_views_data_alter(array &$data) {
  // Source field - imported or local.
  $data['node_field_data']['hs_dashboard_source_field'] = [
    'title' => t('Content source'),
    'help' => t('The source of the content - imported or local.'),
    'field' => [
      'id' => 'hs_dashboard_source_field',
    ],
  ];
  // Join node data to editoria11y_results.
  $data['editoria11y_results']['node'] = [
    'title' => t('Referenced node'),
    'help' => t('Relate this result to its node.'),
    'relationship' => [
      'base' => 'node_field_data',
      'base field' => 'nid',
      'field' => 'entity_id',
      'id' => 'editoria11y_results_node',
      'label' => t('Node from editoria11y_results'),
    ],
  ];
}

/**
 * Implements hook_entity_operation().
 */
function hs_dashboard_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->getEntityTypeId() == 'node') {
    $operations['revision_link'] = [
      'title' => t('Revisions'),
      'url' => Url::fromRoute('entity.node.version_history', ['node' => $entity->id()]),
      'weight' => 10,
    ];
  }
  return $operations;
}

/**
 * Implements hook_user_login().
 */
function hs_dashboard_user_login(UserInterface $account) {
  $shortcut_set_storage = Drupal::entityTypeManager()->getStorage('shortcut_set');
  foreach (HS_DASHBOARD_LOW_LEVEL_ROLES as $role) {
    if ($account->hasRole($role)) {
      // These roles get the limited shortcuts.
      // @see hs_dashboard_shortcut_set_insert()
      $set = $shortcut_set_storage->load('low-level-roles');
      $shortcut_set_storage->assignUser($set, $account);

      // Go to the list of /my-content rather than the Drupal default of /user,
      // unless they're already on their way to some other destination.
      if (!\Drupal::request()->query->has('destination')) {
        \Drupal::request()->query->set('destination', '/my-content');
      }
      return;
    }
  }
  // All other roles get the default shortcuts.
  $set = $shortcut_set_storage->load('default');
  $shortcut_set_storage->assignUser($set, $account);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hs_dashboard_shortcut_set_insert(EntityInterface $entity) {
  // The Shortcut Set is configuration, but the shortcuts within it are content.
  // Create the shortcuts for low-level roles.
  if ($entity->id() === 'low-level-roles') {
    $links = [
      [
        'title' => 'Home',
        'uri' => 'internal:/',
      ],
      [
        'title' => 'My Content',
        'uri' => 'internal:/my-content',
      ],
    ];
    foreach ($links as $link) {
      $shortcut = Shortcut::create([
        'shortcut_set' => 'low-level-roles',
        'title' => $link['title'],
        'link' => [
          'uri' => $link['uri'],
        ],
      ]);
      $shortcut->save();
    }
  }
}
