<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_views_query_alter().
 */
function hs_dashboard_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Finds duplicated published person nodes.
  if ($view->id() === 'duplicate_people' && in_array('node_field_data', $view->getBaseTables())) {
    $sub_query = \Drupal::database()->select('node_field_data', 'sub_query')
      ->fields('sub_query', ['title'])
      ->condition('sub_query.type', 'person')
      ->condition('sub_query.status', '1')
      ->groupBy('sub_query.title')
      ->having('COUNT(sub_query.title) > 1');

      /** @var Drupal\hs_views_helper\Plugin\views\query\Sql $query */
    $query->addWhereExpression(
      NULL,
      'node_field_data.title IN (' . $sub_query->__toString() . ')'
    );
  }
}
