<?php

/**
 * @file
 * hs_theme_helper.module
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_config_schema_info_alter().
 */
function hs_theme_helper_config_schema_info_alter(&$definitions) {
  $definitions['system.site']['mapping']['name_line2'] = [
    'type' => 'string',
    'label' => 'Site name line 2',
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hs_theme_helper_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('system.site');

  $form['site_information']['site_name']['#weight'] = -10;
  $form['site_information']['site_name_line_2'] = [
    '#type' => 'textfield',
    '#title' => t('Site name line 2'),
    '#default_value' => $config->get('name_line2') ?: '',
    '#weight' => -9,
  ];

  $form['site_information']['site_slogan']['#title'] = t('Stanford Affiliation');
  $form['site_information']['site_slogan']['#description'] = t('Stanford University school or administrative unit your site is most associated with.');
  $admin_roles = \Drupal::entityTypeManager()
    ->getStorage('user_role')
    ->getQuery()
    ->condition('is_admin', TRUE)
    ->execute();
  $user_roles = \Drupal::currentUser()->getRoles();

  // Lock the site slogan unless the user has the admin role.
  if (empty(array_intersect($user_roles, $admin_roles))) {
    $form['site_information']['site_slogan']['#attributes']['disabled'] = 'disabled';
  }

  $form['#submit'][] = 'hs_theme_helper_form_system_site_information_settings_submit';
}

/**
 * Form submit handler for basic site settings form.
 *
 * @param array $form
 *   Complete Form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Submitted form state.
 */
function hs_theme_helper_form_system_site_information_settings_submit(array &$form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('system.site')
    ->set('name_line2', $form_state->getValue('site_name_line_2'))
    ->save();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_theme_helper_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] == 'system_branding_block') {
    $line_2 = \Drupal::configFactory()
      ->get('system.site')
      ->get('name_line2');
    $variables['site_name_line_2']['#markup'] = $line_2 ?: '';
  }
}
