<?php

/**
 * @file
 * Primary module hooks for H&S Curriculum Map module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hs_cmap_taxonomy_vocabulary_insert(EntityInterface $vocabulary) {
  // Vocabularies are config, but taxonomy terms are content.
  // So when the vocabulary is created, add our default terms.
  if ($vocabulary->id() !== 'hs_curriculum_requirement_type') {
    return;
  }
  $requirement_types = [
    [
      'name' => 'Core',
      'field_hs_curriculum_course_color' => 'lagunita-light',
    ],
    [
      'name' => 'Elective',
      'field_hs_curriculum_course_color' => 'digital-red',
    ],
    [
      'name' => 'Concentration',
      'field_hs_curriculum_course_color' => 'plum',
    ],
    [
      'name' => 'Honors',
      'field_hs_curriculum_course_color' => 'poppy-light',
    ],
    [
      'name' => 'Upper-Division',
      'field_hs_curriculum_course_color' => 'olive-dark',
    ],
    [
      'name' => 'Thesis',
      'field_hs_curriculum_course_color' => 'brick-dark',
    ],
    [
      'name' => 'Other',
      'field_hs_curriculum_course_color' => 'grey-500',
    ],
  ];
  foreach ($requirement_types as $weight => $type) {
    $term = [
      'vid' => 'hs_curriculum_requirement_type',
      'name' => $type['name'],
      'parent' => [],
      'weight' => $weight,
      'field_hs_curriculum_course_color' => [
        'value' => $type['field_hs_curriculum_course_color'],
      ],
    ];
    // During the insert hook we don't yet have custom fields.  So wait until
    // later to save the term.
    register_shutdown_function('_hs_cmap_save_taxonomy_term', $term);
  }
}

/**
 * Create a taxonomy term.
 *
 * @param array $data
 *   As required by Drupal\taxonomy\Entity\Term::create().
 *
 * @return void
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _hs_cmap_save_taxonomy_term(array $data): void {
  $term = Term::create($data);
  $term->save();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function hs_cmap_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\taxonomy\Entity\Term $term */
  $term = $form_state->getFormObject()->getEntity();
  if ($term->bundle() !== 'hs_curriculum_requirement_type') {
    return;
  }
  // Hide the standard taxonomy things that don't make sense for this bundle.
  $form['revision_information']['#access'] = FALSE;
  $form['relations']['#access'] = FALSE;
}
