<?php

/**
 * @file
 * Update functions for hs_cmap module.
 */

/**
 * Grant permissions to site manager role.
 */
function hs_cmap_update_10001() {
  user_role_grant_permissions('site_manager', [
    'create terms in hs_curriculum_requirement_type',
    'delete terms in hs_curriculum_requirement_type',
    'edit terms in hs_curriculum_requirement_type',
    'use text format bold_italics_links',
  ]);
}
