<?php

/**
 * @file
 * Primary module hooks for H&S Curriculum Map module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\WidgetBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hs_cmap_taxonomy_vocabulary_insert(EntityInterface $vocabulary): void {
  // Vocabularies are config, but taxonomy terms are content.
  // So when the vocabulary is created, add our default terms.
  if ($vocabulary->id() !== 'hs_curriculum_requirement_type') {
    return;
  }
  $requirement_types = [
    [
      'name' => 'Core',
      'field_hs_curriculum_course_color' => 'lagunita-light',
    ],
    [
      'name' => 'Elective',
      'field_hs_curriculum_course_color' => 'digital-red',
    ],
    [
      'name' => 'Capstone',
      'field_hs_curriculum_course_color' => 'sky-dark',
    ],
    [
      'name' => 'Concentration',
      'field_hs_curriculum_course_color' => 'plum',
    ],
    [
      'name' => 'Foundation',
      'field_hs_curriculum_course_color' => 'spirited',
    ],
    [
      'name' => 'Honors',
      'field_hs_curriculum_course_color' => 'poppy-light',
    ],
    [
      'name' => 'Independent Study',
      'field_hs_curriculum_course_color' => 'bay-dark',
    ],
    [
      'name' => 'Thesis',
      'field_hs_curriculum_course_color' => 'brick-dark',
    ],
    [
      'name' => 'Upper-Division',
      'field_hs_curriculum_course_color' => 'olive-dark',
    ],
    [
      'name' => 'WIM (Writing in the Major)',
      'field_hs_curriculum_course_color' => 'plum',
    ],
    [
      'name' => 'Other',
      'field_hs_curriculum_course_color' => 'grey-500',
    ],
  ];
  foreach ($requirement_types as $weight => $type) {
    $term = [
      'vid' => 'hs_curriculum_requirement_type',
      'name' => $type['name'],
      'parent' => [],
      'weight' => $weight,
      'field_hs_curriculum_course_color' => [
        'value' => $type['field_hs_curriculum_course_color'],
      ],
    ];
    // During the insert hook we don't yet have custom fields.  So wait until
    // later to save the term.
    register_shutdown_function('_hs_cmap_save_taxonomy_term', $term);
  }
}

/**
 * Create a taxonomy term.
 *
 * @param array $data
 *   As required by Drupal\taxonomy\Entity\Term::create().
 *
 * @return void
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _hs_cmap_save_taxonomy_term(array $data): void {
  $term = Term::create($data);
  $term->save();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function hs_cmap_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state): void {
  /** @var \Drupal\taxonomy\Entity\Term $term */
  $term = $form_state->getFormObject()->getEntity();
  if ($term->bundle() !== 'hs_curriculum_requirement_type') {
    return;
  }

  // Hide the standard taxonomy things that don't make sense for this bundle.
  $form['revision_information']['#access'] = FALSE;
  $form['relations']['#access'] = FALSE;
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function hs_cmap_field_widget_single_element_form_alter(&$element, FormStateInterface $form_state, $context): void {
  if (!isset($element['#paragraph_type'])) {
    return;
  }
  $delta = $context['delta'];
  $paragraph_bundle = $element['#paragraph_type'];

  /** @var \Drupal\field\Entity\FieldConfig $field_definition */
  $field_definition = $context['items']->getFieldDefinition();
  $content_field_name = $field_definition->getName();

  // @see \Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget::formElement()
  $widgetState = WidgetBase::getWidgetState($element['#field_parents'], $content_field_name, $form_state);

  // If this is an empty paragraph, do nothing.
  if (!isset($widgetState['paragraphs'][$delta])) {
    return;
  }

  // Don't act on Paragraph previews.
  if (!Element::children($element['subform'])) {
    return;
  }

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $widgetState['paragraphs'][$delta]['entity'];

  // Set default year label, incrementing on the previous.
  if (
    $paragraph_bundle === 'hs_cmap_year'
    && empty($element['subform']['field_hs_cmap_year_year']['widget'][0]['value']['#default_value'])
  ) {
    $element['subform']['field_hs_cmap_year_year']['widget'][0]['value']['#default_value'] = 'Year ' . ($delta + 1);
  }

  // Set default quarter, incrementing on the previous.
  if (
    $paragraph_bundle === 'hs_cmap_qtr'
    && empty($element['subform']['field_hs_cmap_qtr_quarter']['widget']['#default_value'])
  ) {
    $options = $element['subform']['field_hs_cmap_qtr_quarter']['widget']['#options'];
    if (isset($options['_none'])) {
      unset($options['_none']);
    }
    $options = array_keys($options);
    $default = $options[$delta % count($options)];
    $element['subform']['field_hs_cmap_qtr_quarter']['widget']['#default_value'] = [$default];
  }

  // Set "Core" as the default Requirement Type.
  if (
    $paragraph_bundle === 'hs_cmap_qtr_crs'
    && empty($element['subform']['field_hs_cmap_crs_requirement']['widget']['#default_value'])
  ) {
    $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
    $terms = $term_storage->loadByProperties([
      'vid' => 'hs_curriculum_requirement_type',
      'name' => 'Core',
    ]);
    if ($core_tid = key($terms)) {
      $element['subform']['field_hs_cmap_crs_requirement']['widget']['#default_value'] = [$core_tid];
    }
  }

}
