hs_courses_importer.hs_course_tag.*:
  type: config_entity
  label: 'Course Tag Translation config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    tag:
      type: string
      label: 'Explore Courses Tag'
