hs_courses_importer.importer_settings:
  type: config_entity
  label: 'Course Importer settings.'
  mapping:
    base_url:
      type: string
      label: 'Local url helpful for use in CRON'
    urls:
      type: sequence
      label: 'Importer URLs'
      sequence:
        type: string
        label: 'Importer URL'

hs_courses_importer.hs_course_tag.*:
  type: config_entity
  label: 'Course Tag Translation config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    tag:
      type: string
      label: 'Explore Courses Tag'
