su_humsci_profile.settings:
  type: config_object
  mapping:
    new_themes:
      type: sequence
      label: 'Newer themes'
      sequence:
        type: string
        label: 'Theme name'
    allowed:
      type: mapping
      label: 'Allowed settings'
      mapping:
        condition_plugins:
          type: sequence
          label: 'Allowed Condition Plugin IDS'
          sequence:
            type: string
            label: 'Condition Plugin ID'