allow_cli: false
print: ''
credential_provider: multikey
credentials:
  multikey:
    user_pass_key: hs_shield_key
shield_enable: true
whitelist: ''
paths: "/.well-known\r\n/.well-known/*"
domains: ''
method: 0
