<?php

/**
 * @file
 * Provides a humsci entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\hs_entities\Entity\HsEntity;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function hs_entities_theme() {
  return [
    'hs_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for humsci entity templates.
 *
 * Default template: hs-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the humsci entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_hs_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function hs_entities_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish humsci entities.
      $storage = \Drupal::entityTypeManager()->getStorage('hs_entity');
      $hs_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($hs_entity_ids) as $hs_entity) {
        $hs_entity->set('status', FALSE);
        $hs_entity->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize humsci entities.
      $storage = \Drupal::entityTypeManager()->getStorage('hs_entity');
      $hs_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($hs_entity_ids) as $hs_entity) {
        $hs_entity->setOwnerId(0);
        $hs_entity->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function hs_entities_user_predelete(UserInterface $account) {
  // Delete humsci entities.
  $storage = \Drupal::entityTypeManager()->getStorage('hs_entity');
  $hs_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $hs_entities = $storage->loadMultiple($hs_entity_ids);
  $storage->delete($hs_entities);
  // Delete old revisions.
  $hs_entity_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->execute();
  foreach (array_keys($hs_entity_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
