<?php

/**
 * @file
 * Contains react_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function react_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_paragraphs module.
    case 'help.page.react_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field type for paragraphs that uses React decoupling for the form and display') . '</p>';
      return $output;

    default:
  }
}
