<?php

/**
 * @file
 * Contains react_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function react_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_paragraphs module.
    case 'help.page.react_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field type for paragraphs that uses React decoupling for the form and display') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function react_paragraphs_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_state->get('entity_browser_current_widget')) {
    $cardinality = \Drupal::requestStack()
      ->getCurrentRequest()->query->get('reactCard');
    if ((int) $cardinality >= 1) {
      $form_state->set([
        'entity_browser',
        'validators',
        'cardinality',
        'cardinality',
      ], (int) $cardinality);
    }
  }
}
