hs_algolia.settings:
  type: config_object
  label: 'Algolia search settings'
  mapping:
    application_id:
      type: string
      label: 'Algolia application ID'
    api_key:
      type: string
      label: 'ID of the key entity holding the Algolia write API key'
    index_name:
      type: string
      label: 'Algolia index name'
