name: suhumsci
type: drupal9
docroot: docroot
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
  - ethicsinsociety
  - anthropology
  - archaeology
  - art
  - biology
  - chemistry
  - classics
  - economics
  - english
  - history
  - mathematics
  - philosophy
  - physics
  - psychology
  - sociology
  - aaai
  - aaas
  - aarcs
  - africanstudies
  - amstudies
  - anthrohandbook
  - artexhibitions
  - arthandbook
  - aviditacharya-humsci
  - bingschool
  - biologyvirtualshowcase
  - bsurp
  - buddhiststudies
  - cas
  - ccsre
  - ceas
  - cesta
  - clas
  - cmbprogram
  - cmems
  - cqmd
  - creativewriting
  - creees
  - culture-emotion-lab
  - datasciencemajor
  - dennylab
  - development-humsci
  - dlcl
  - dsresearch
  - duboislab
  - ealc
  - em1060
  - facultyaffairs-humsci
  - feminist
  - finance-humsci
  - francestanford
  - gavin-wright-humsci
  - gender
  - globalcurrents
  - grandtour
  - gus-humsci
  - hps
  - hs-colorful
  - hs-design
  - hs-fps
  - hs-sandbox
  - hs-sandbox-1
  - hs-sandbox-2
  - hs-sandbox-3
  - hs-testing-sandbox
  - hs-traditional
  - hsbi
  - hshr
  - hsweb-referencetraditional
  - hsweb-userguide
  - humanbiology
  - humanitiescore
  - humanrights
  - insidehs
  - integrativeoceans
  - internationalrelations
  - iranianstudies
  - iriss
  - islamicstudies
  - it-humsci
  - it-humsci2023
  - jewishstudies
  - jrbp2025
  - justsocieties
  - language
  - linguistics
  - lowe
  - mcs
  - medicalhumanities
  - memorylab
  - middleeast
  - morrisoninstitute
  - mrc
  - mtl
  - music
  - philit
  - planning-humsci
  - politicalscience
  - popstudies
  - ptarmigan
  - publichumanities
  - publicpolicy
  - publicpulse
  - religiousstudies
  - researchadmin-humsci
  - sgs
  - shenlab
  - sitp
  - siw
  - sociology2025
  - southasia
  - stanfordsciencefellows
  - statistics
  - sts
  - suac
  - symsys
  - tessier-lavigne-lab
  - texttechnologies
  - urbanstudies
  - west
  - womensleadership
  - womensleadershipcp
additional_fqdns: []
database:
    type: mysql
    version: "5.7"
use_dns_when_possible: true
disable_settings_management: true
composer_version: "2.8.2"
web_environment: []
corepack_enable: false
additional_services:
  - selenium

hooks:
  post-start:
    - exec-host: cp .ddev/ddev.sites.php docroot/sites/local.sites.php
    - exec: composer install
    - exec: /var/www/html/vendor/bin/blt blt:init:settings
    - exec: /var/www/html/.ddev/scripts/configure-local-settings.sh
    - exec: /var/www/html/.ddev/scripts/create-local-databases.sh
