<?php

/**
 * @file
 * Contains hs_mathematics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hs_mathematics_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hs_mathematics module.
    case 'help.page.hs_mathematics':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Temporary module to build mathematics site') . '</p>';
      return $output;

    default:
  }
}
