<?php

/**
 * @file
 * hs_paragraph_types.module
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Entity\EntityInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_paragraph_types_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  if (in_array($bundle, ['hs_collection', 'hs_priv_collection'])) {
    $variables['#attached']['library'][] = 'hs_paragraph_types/hs_collection';
    $variables['attributes']['class'][] = 'hs-paragraph-style';

    if (!$paragraph->hasField('field_bg_color') || !$paragraph->hasField('field_bg_color_width')) {
      return;
    }

    // Replace underscores with hyphens in the bg_color value.
    $bg_color = Html::cleanCssIdentifier($paragraph->get('field_bg_color')->getString());

    // Append "-well" to the bg_color.
    $bg_width = $paragraph->get('field_bg_color_width')->getString();
    if (!empty($bg_color)) {
      $bg_width_class = $bg_width == 'full_width' ? 'well-full-width' : 'well';
      $bg_color .= '-well';
      $variables['attributes']['class'][] = 'hs-paragraph-style--' . $bg_width_class;
      $variables['attributes']['class'][] = 'hs-paragraph-style--' . $bg_color;
    }
  }
  elseif ($bundle == 'hs_sptlght_slder') {
    if (!$paragraph->hasField('field_bg_color_width')) {
      return;
    }

    $bg_width = $paragraph->get('field_bg_color_width')->getString();
    if ($bg_width == 'full_width') {
      $variables['attributes']['class'][] = 'paragraph--style--full-width';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_paragraph_types_preprocess_field__field_hs_collection_items(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['element']['#object'];
  $items_per_row = (int) $paragraph->get('field_hs_collection_per_row')
    ->getString();
  $variables['attributes']['class'][] = "item-per-row--$items_per_row";
  $variables['#attached']['library'][] = 'hs_paragraph_types/hs_collection';
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function hs_paragraph_types_field_widget_complete_paragraphs_form_alter(array &$field_widget_form, FormStateInterface $form_state, array $context) {
  // Hide the 'Background Color Width' field for Spotlight Slider paragraphs
  // in the full width region.
  if (
    !empty($field_widget_form['widget']['#field_name']) &&
    $field_widget_form['widget']['#field_name'] == 'field_hs_page_hero'
  ) {
    foreach (Element::children($field_widget_form['widget']) as $key) {
      if (!is_int($key)) {
        continue;
      }
      if (
        $field_widget_form['widget'][$key]['#paragraph_type'] == 'hs_sptlght_slder' &&
        isset($field_widget_form['widget'][$key]['subform']['field_bg_color_width'])
      ) {
        $field_widget_form['widget'][$key]['subform']['field_bg_color_width']['#access'] = FALSE;
      }
    }
  }
  $elements_to_change = [
    'field_hs_carousel_slides',
    'field_hs_sptlght_sldes',
    'field_hs_page_components',
    'field_hs_priv_page_components',
  ];
  // We need the field name to alter the correct element.
  if (
    empty($field_widget_form['widget']['#field_name']) ||
    !in_array($field_widget_form['widget']['#field_name'], $elements_to_change)
  ) {
    return;
  }
  switch ($field_widget_form['widget']['#field_name']) {
    case 'field_hs_carousel_slides':
      if (empty($field_widget_form['widget']['add_more'])) {
        return;
      }
      // Change the add button label for field_hs_carousel_slides.
      $new_label = 'Banner image with text box';
      $field_widget_form['widget']['add_more']['add_more_button_hs_hero_image']['#value'] = t('Add @type', [
        '@type' => $new_label,
      ]);
      // Change the paragraph type label for hs_hero_image embedded in
      // hs_carousel.
      foreach (Element::children($field_widget_form['widget']) as $key) {
        // Only alter markup in field widget elements.
        if (!is_int($key)) {
          continue;
        }
        $field_widget_form['widget'][$key]['top']['type']['label']['#markup'] = t('@label', ['@label' => $new_label]);
      }
      break;

    case 'field_hs_sptlght_sldes':
      // Change the spotlight widget title.
      $new_label = 'Spotlight(s)';
      $field_widget_form['widget']['#title'] = t('@label', ['@label' => $new_label]);
      if (!empty($field_widget_form['widget']['add_more']['#suffix'])) {
        // Change the paragraph type label for the add more button.
        $field_widget_form['widget']['add_more']['#suffix'] = t('to %type', [
          '%type' => $new_label,
        ]);
      }
      break;

    case 'field_hs_page_components':
    case 'field_hs_priv_page_components':
      // There are multiple issues with setting and removing the required state
      // from paragraph fields when using the `conditional_fields` module, so
      // use form alter to use the states api instead.
      // @see https://www.drupal.org/project/conditional_fields/issues/3344587
      // Check that hs_collection is the correct paragraph type
      // and correct fields are present.
      foreach (Element::children($field_widget_form['widget']) as $key) {
        if (!is_int($key)) {
          continue;
        }
        $element = $field_widget_form['widget'][$key];
        if (
          empty($element['#paragraph_type']) ||
          !in_array($element['#paragraph_type'], ['hs_collection', 'hs_priv_collection']) ||
          empty($element['subform']['field_title']) ||
          empty($element['subform']['field_title_settings'])
        ) {
          continue;
        }
        // Build title settings name for this component.
        $title_settings_name = '';
        foreach ($element['subform']['field_title_settings']['widget']['#field_parents'] as $delta) {
          if (!empty($title_settings_name)) {
            $delta = "[$delta]";
          }
          $title_settings_name .= $delta;
        }
        $title_settings_name .= '[field_title_settings]';

        $header_conditions = [
          ':input[name="' . $title_settings_name . '"]' => [
            [
              'value' => 'collection_title_visible',
            ],
            'or',
            [
              'value' => 'collection_title_sr_only',
            ],
          ],
        ];

        $element['subform']['field_title']['widget'][0]['value']['#states'] = [
          'required' => [$header_conditions],
          'visible' => [$header_conditions],
        ];
        $field_widget_form['widget'][$key] = $element;
      }
      break;
  }
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function hs_paragraph_types_field_widget_complete_options_select_form_alter(array &$field_widget_form, FormStateInterface &$form_state, array $context) {
  // Change the default "None" label for certain select fields.
  if (!isset($context['items'])) {
    return;
  }

  $none_labels = [
    'field_accordion_style' => t('Default'),
  ];
  $field_name = $context['items']->getName();

  if (array_key_exists($field_name, $none_labels)) {
    $field_widget_form['widget']['#options']['_none'] = $none_labels[$field_name];
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function hs_paragraph_types_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  if (!$entity instanceof ParagraphInterface) {
    return;
  }

  switch ($entity->bundle()) {
    case 'hs_postcard':
      if (
        !$entity->hasField('field_hs_postcard_layout') ||
        !$entity->hasField('field_hs_postcard_vertical_style')
      ) {
        break;
      }

      $layout = $entity->get('field_hs_postcard_layout')->value;
      if ($layout == 'horizontal') {
        $view_mode = 'preview';
      }
      elseif ($layout == 'vertical') {
        $style = $entity->get('field_hs_postcard_vertical_style')->value;
        switch ($style) {
          case 'stacked':
            $view_mode = 'vertical_button_card';
            break;

          case 'two_color':
            $view_mode = 'token';
            break;

          default:
            $view_mode = 'default';
        }
      }
      break;

    case 'hs_spotlight':
      if (!$entity->hasField('field_hs_spotlight_image_height') || $entity->get('field_hs_spotlight_image_height')->isEmpty()) {
        break;
      }
      $view_mode = $entity->get('field_hs_spotlight_image_height')->value == 'tall' ? 'default' : 'preview';
      break;

    case 'hs_banner':
      if (!$entity->hasField('field_hs_banner_image_height') || $entity->get('field_hs_banner_image_height')->isEmpty()) {
        break;
      }
      $view_mode = $entity->get('field_hs_banner_image_height')->value == 'tall' ? 'preview' : 'default';
      break;

    case 'hs_callout_box':
      if (!$entity->hasField('field_hs_callout_background') || $entity->get('field_hs_callout_background')->isEmpty()) {
        break;
      }
      $view_mode = $entity->get('field_hs_callout_background')->value == 'light' ? 'hs_well' : 'default';
      break;

    case 'hs_clr_bnd':
      if (!$entity->hasField('field_hs_clr_bnd_width') || $entity->get('field_hs_clr_bnd_width')->isEmpty()) {
        break;
      }
      $view_mode = $entity->get('field_hs_clr_bnd_width')->value == 'full-width' ? 'default' : 'preview';
      break;

    case 'stanford_gallery':
      if ($entity->hasField('field_hs_gallery_style') && !$entity->get('field_hs_gallery_style')->isEmpty()) {
        $view_mode = $entity->get('field_hs_gallery_style')->value == 'slideshow' ? 'hs_gallery_slideshow' : 'default';
      }
      break;
  }
}
