# .github/workflows/acquia-cleanup.yml
# Clean up stale site backups and branches on Acquia
name: Acquia Cleanup
# on:
#   schedule:
#     # Run on Tuesdays at Midnight (Monday Nights)
#     - cron: '0 0 * * 2'
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  acquia_cleanup:
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:php8.3
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
          key: 1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
            1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-
            1.0-${{ hashFiles('blt/blt.yml') }}-
      - name: Clean up backups and branches
        env:
          SLACK_NOTIFICATION_URL: ${{ secrets.SLACK_NOTIFICATION_URL }}
          ACQUIA_KEY: ${{ secrets.ACQUIA_KEY }}
          ACQUIA_SECRET: ${{ secrets.ACQUIA_SECRET }}
        run: |
          composer install -n &&
          blt blt:telemetry:disable --no-interaction &&
          # blt humsci:clean-backups &&
          blt humsci:clean-branches
