name: Content Staging
on:
  schedule:
    - cron: '0 0 * * 3'
jobs:
  Copy-Prod-Database-Down:
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:php8.3
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
          key: 1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
            1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-
            1.0-${{ hashFiles('blt/blt.yml') }}-
      - name: Copy databases
        env:
          SLACK_NOTIFICATION_URL: ${{ secrets.SLACK_NOTIFICATION_URL }}
          ACQUIA_KEY: ${{ secrets.ACQUIA_KEY }}
          ACQUIA_SECRET: ${{ secrets.ACQUIA_SECRET }}
        run: |
          composer install -n &&
          blt blt:telemetry:disable --no-interaction &&
          blt stage --no-interaction
