name: Drupal PHP CodeSniffer
on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run_phpcs:
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:php8.3
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
          key: 1.0-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
      - name: Run PHPCS
        run: |
          composer install -n &&
          vendor/bin/phpcs --standard=./phpcs.xml
