<?php

/**
 * @file
 * hs_row_display.module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function hs_row_display_paragraph_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'hs_row') {
    $build['#attached']['library'][] = 'hs_row_display/hs_row';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function hs_row_display_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'field_hs_row_components') {
    $variables['attributes']['class'][] = 'counted-items-' . count($variables['items']);
  }
}
